import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const SITE = 'https://ravoraapps.tech';

/*
  A committed file rather than an `opengraph-image.tsx` metadata route. That
  route emits an extensionless artifact, which GitHub Pages — where this site
  is served from — hands back as application/octet-stream, and social crawlers
  reject it. The trade is that the card is regenerated by hand when the brand
  changes rather than at every build.
*/
const OG_IMAGE = {
  url: '/og.png',
  width: 1200,
  height: 630,
  alt: 'Ravora Apps — modern solutions, accelerated with AI',
};

const description =
  'Ravora Apps is a creative studio in Chennai building and operating modern products — accelerated with AI, built with a motive.';

export const metadata: Metadata = {
  metadataBase: new URL(SITE),
  title: {
    default: 'Ravora Apps | Modern solutions, accelerated with AI',
    template: '%s',
  },
  description,
  applicationName: 'Ravora Apps',
  keywords: [
    'Ravora Apps',
    'creative studio Chennai',
    'product studio India',
    'AI product development',
    'software studio Chennai',
  ],
  alternates: {
    canonical: '/',
  },
  openGraph: {
    title: 'Ravora Apps',
    description,
    url: SITE,
    siteName: 'Ravora Apps',
    locale: 'en_IN',
    type: 'website',
    images: [OG_IMAGE],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Ravora Apps',
    description,
    images: [OG_IMAGE.url],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
};

/*
  Only facts we can actually stand behind go in the business profile —
  no invented phone numbers, founding dates, or social profiles. Anything
  further gets added when it genuinely exists.
*/
const organizationSchema = {
  '@context': 'https://schema.org',
  '@type': 'Organization',
  '@id': `${SITE}/#organization`,
  name: 'Ravora Apps',
  legalName: 'Ravora Apps OPC Private Limited',
  url: SITE,
  logo: `${SITE}/ravora-logo.png`,
  description,
  email: 'hello@ravoraapps.tech',
  address: {
    '@type': 'PostalAddress',
    addressLocality: 'Chennai',
    addressRegion: 'Tamil Nadu',
    addressCountry: 'IN',
  },
  contactPoint: {
    '@type': 'ContactPoint',
    contactType: 'business enquiries',
    email: 'hello@ravoraapps.tech',
    areaServed: 'IN',
    availableLanguage: ['en'],
  },
  owns: [
    { '@type': 'SoftwareApplication', name: 'Wireneurons', url: 'https://wireneurons.com' },
    { '@type': 'SoftwareApplication', name: 'Aubstrac', url: 'https://aubstrac.com' },
  ],
};

const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  '@id': `${SITE}/#website`,
  url: SITE,
  name: 'Ravora Apps',
  description,
  publisher: { '@id': `${SITE}/#organization` },
  inLanguage: 'en-IN',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    /*
      The font variables must live on <html>, not <body>. globals.css maps
      --font-sans to --font-geist-sans at :root; declaring them a level lower
      left that reference unresolvable, so font-family fell back to the
      browser default serif across the whole site.
    */
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
      suppressHydrationWarning
    >
      <body suppressHydrationWarning>
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify([organizationSchema, websiteSchema]),
          }}
        />
        <a href="#content" className="skipLink">
          Skip to content
        </a>
        <Header />
        <main id="content">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
